export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';

export const UPDATE_ASSIGNED_LIST = 'UPDATE_ASSIGNED_LIST';

export const UPDATE_INPROGRESS_LIST = 'UPDATE_INPROGRESS_LIST';

export const UPDATE_DONE_LIST = 'UPDATE_DONE_LIST';

export const UPDATE_TASK_BOARD = 'UPDATE_TASK_BOARD';

export const CLEAR_TASK_BOARD = 'CLEAR_TASK_BOARD';
