export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';

export const UPDATE_ASSIGNED_LIST = 'UPDATE_ASSIGNED_LIST';

export const UPDATE_INPROGRESS_LIST = 'UPDATE_INPROGRESS_LIST';

export const UPDATE_DONE_LIST = 'UPDATE_DONE_LIST';
